import{S as d,i}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const l=document.querySelector(".result-gallery");let h=new d(".result-gallery a",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({largeImageURL:s,webformatURL:a,tags:e,likes:r,views:n,comments:u,downloads:p})=>`
        <li class="result-item">
            <a href="${s}" class="picture-link">
                <img src="${a}" alt="${e}" loading="lazy" class="item-image" />
            </a>
            <div class="picture-text">
                <p class="text"><span class="bold-text">Likes</span> ${r}</p>
                <p class="text"><span class="bold-text">Views</span> ${n}</p>
                <p class="text"><span class="bold-text">Comments</span> ${u}</p>
                <p class="text"><span class="bold-text">Downloads</span> ${p}</p>
            </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",t),h.refresh()}function m(){l.innerHTML=""}function g(o){const t=document.querySelector(".search-text");document.querySelector(".search-form").addEventListener("submit",a=>{a.preventDefault();const e=t.value.trim();e!==""&&o(e),t.value=""})}const y=void 0;async function x(o){const t=new URLSearchParams({key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`https://pixabay.com/api/?${t}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).then(s=>s.hits).catch(s=>{throw s})}const c=document.querySelector(".loading-text");g(o=>{m(),c.classList.remove("is-hidden"),x(o).then(t=>{if(t.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t)}).catch(t=>{i.error({title:"Error",message:"Something went wrong while connecting to the server. Please try again later!",position:"topRight"}),console.log(t)}).finally(()=>{c.classList.add("is-hidden")})});
//# sourceMappingURL=index.js.map
